### ISSUE TITLE
Slideshow back button

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#788]
After selection of a slideshow, the slideshow is displayed but there is no option to navigate back to the selection screen (other than using the menu).

We should think of a way to navigate back.

**Comment by sheepyhollow** [comment]
1st idea: Use the previous button `<` in the first slide and the next button `>` on the last slide of a show to jump to the selection

Additionally we might have a level up `^` button somewhere - but where?

**Comment by kerstinhartmann** [comment]
Maybe we could use a button that looks a little different? e.g. "`<<`"
Especially on the last page it could be irritating to leave the whole slideshow by using the next button `<`.

**Comment by sheepyhollow** [comment]
Good idea! I was thinking about putting `^` in the last slide (instead of `>`), but double brackets might eventually look better.

**Comment by sheepyhollow** [comment]
Hmmm... there is just no fitting icon and I think we should stick to the [Material Icons](https://fonts.google.com/icons?selected=Material+Icons)

**Comment by kerstinhartmann** [comment]
What about this one? We can only use it for one direction, right? [double_arrow](https://fonts.google.com/icons?selected=Material%20Icons%3Adouble_arrow) 
 
 Otherwise maybe one of these? 
  [Exit to App](https://fonts.google.com/icons?selected=Material%20Icons%3Aexit_to_app)
  [Done all](https://fonts.google.com/icons?selected=Material%20Icons%3Adone_all)
  [Eject](https://fonts.google.com/icons?selected=Material%20Icons%3Aeject)
  or just simply the [X](https://fonts.google.com/icons?selected=Material%20Icons%3Aclose)?

**Comment by sheepyhollow** [comment]
The `double_arrow` is styled very differently compared to the normal navigation arrows.
The other icons are somehow not really intuitive, although I might let myself talk into `Done all`, which somehow makes sense.
But the `X` is the most convincing idea by now.
*But* we actually do have a way to use self-built icons. I might just double the `navigate_next` icon and give it a try.

**Comment by sheepyhollow** [comment]
Well... it's possible, but no one said it would be easy 😅
